#!/usr/bin/ash

run_hook() {
    # Configure TPM
    chown tss:tss /dev/tpm0
    chmod 600 /dev/tpm0
    sleep 1

    # Start tcsd
    if [ -f /usr/bin/tcsd ]; then
        /sbin/tcsd
    fi

    # Create necessary lo interface
    ifconfig lo 127.0.0.1
    echo 127.0.0.1 localhost > /etc/hosts

    # Get key from TPM NVRAM
    echo TPM... getting secret from NVRAM
    /etc/tpm-secret/tpm_getsecret.sh > /secret_key.bin
    chmod 0400 /secret_key.bin
}
